- name: Install Xorg packages
  pacman:
    name:
      - xorg-server
      - xorg-xinit
  become: true

- name: Install Xorg test utilities
  pacman:
    name:
      - xorg-xev
      - xorg-xinput
  become: true

- name: Install autorandr for monitor hotplugging
  pacman:
    name: autorandr
  become: true

- name: Set correct X11 keymap
  template:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/
    mode: 0644

- name: Copy pointer configuration file
  copy:
    src: 30-mouse.conf
    dest: /etc/X11/xorg.conf.d/
    mode: 0644
