---
- name: Define if dotfiles are installed
  stat: path=/home/{{ user.name }}/.cfg
  register: dotfiles_state

- name: Run install tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
