cron_intervals: 10 # in minutes
project_link: "github.com/stiliajohny/Ansible-Provisioning.git"
inventory: "pull-provisioning-execution"
playbook: "pull-provisioning-execution.yml"
logfile: "/var/log/ansible.log"
